POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"

}

###
GET http://localhost:3000/posts/getallposts

###

POST http://localhost:3000/posts/addpost
Content-Type: application/json

{
    "title": "title2",
    "body": "body1"

}

###

GET http://localhost:3000/posts/select/35

###
GET http://localhost:3000/posts/deleteall

###
GET http://localhost:3000/posts/select/36/delete

###
POST http://localhost:3000/posts/select/37/update
Content-Type: application/json

{
    "body": "new text"
}


